name: Generate SVG Wallpaper

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # Allow manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: |
        pip install poetry
      working-directory: hex_wallpaper

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
      working-directory: hex_wallpaper

    - name: Run generator
      run: |
        poetry run python -m hex_wallpaper.cli
      working-directory: hex_wallpaper

    - name: Upload generated SVG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: wallpaper
        path: src/hex_wallpaper/output.svg
